[package]
name = "install_cosmic"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
apt-parser = "1.0.6"
rust-apt = "0.8.0"
surf = "2.3.2"
tempdir = "0.3.7"
tokio = { version = "1.44.2", features = ["macros", "rt", "rt-multi-thread"] }
